// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: searching/searching.proto

package searching

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SearchingService_Search_FullMethodName       = "/searching_service.SearchingService/Search"
	SearchingService_SearchVideos_FullMethodName = "/searching_service.SearchingService/SearchVideos"
	SearchingService_SearchImages_FullMethodName = "/searching_service.SearchingService/SearchImages"
)

// SearchingServiceClient is the client API for SearchingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Define the SearchingService
type SearchingServiceClient interface {
	Search(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	SearchVideos(ctx context.Context, in *VideoSearchRequest, opts ...grpc.CallOption) (*VideoSearchResponse, error)
	SearchImages(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*ImageResponse, error)
}

type searchingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchingServiceClient(cc grpc.ClientConnInterface) SearchingServiceClient {
	return &searchingServiceClient{cc}
}

func (c *searchingServiceClient) Search(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, SearchingService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchingServiceClient) SearchVideos(ctx context.Context, in *VideoSearchRequest, opts ...grpc.CallOption) (*VideoSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoSearchResponse)
	err := c.cc.Invoke(ctx, SearchingService_SearchVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchingServiceClient) SearchImages(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*ImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageResponse)
	err := c.cc.Invoke(ctx, SearchingService_SearchImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchingServiceServer is the server API for SearchingService service.
// All implementations must embed UnimplementedSearchingServiceServer
// for forward compatibility.
//
// Define the SearchingService
type SearchingServiceServer interface {
	Search(context.Context, *QueryRequest) (*SearchResponse, error)
	SearchVideos(context.Context, *VideoSearchRequest) (*VideoSearchResponse, error)
	SearchImages(context.Context, *QueryRequest) (*ImageResponse, error)
	mustEmbedUnimplementedSearchingServiceServer()
}

// UnimplementedSearchingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchingServiceServer struct{}

func (UnimplementedSearchingServiceServer) Search(context.Context, *QueryRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedSearchingServiceServer) SearchVideos(context.Context, *VideoSearchRequest) (*VideoSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchVideos not implemented")
}
func (UnimplementedSearchingServiceServer) SearchImages(context.Context, *QueryRequest) (*ImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchImages not implemented")
}
func (UnimplementedSearchingServiceServer) mustEmbedUnimplementedSearchingServiceServer() {}
func (UnimplementedSearchingServiceServer) testEmbeddedByValue()                          {}

// UnsafeSearchingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchingServiceServer will
// result in compilation errors.
type UnsafeSearchingServiceServer interface {
	mustEmbedUnimplementedSearchingServiceServer()
}

func RegisterSearchingServiceServer(s grpc.ServiceRegistrar, srv SearchingServiceServer) {
	// If the following call pancis, it indicates UnimplementedSearchingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchingService_ServiceDesc, srv)
}

func _SearchingService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchingServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchingService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchingServiceServer).Search(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchingService_SearchVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchingServiceServer).SearchVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchingService_SearchVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchingServiceServer).SearchVideos(ctx, req.(*VideoSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchingService_SearchImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchingServiceServer).SearchImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchingService_SearchImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchingServiceServer).SearchImages(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchingService_ServiceDesc is the grpc.ServiceDesc for SearchingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "searching_service.SearchingService",
	HandlerType: (*SearchingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchingService_Search_Handler,
		},
		{
			MethodName: "SearchVideos",
			Handler:    _SearchingService_SearchVideos_Handler,
		},
		{
			MethodName: "SearchImages",
			Handler:    _SearchingService_SearchImages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "searching/searching.proto",
}
